# This compose reuses an image for multiple containers. Because of this it should be built in advance with:
# docker build -t bogoslov .

services:
  db:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=bogoslov
      - POSTGRES_USER=bogoslov
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5732:5432
    volumes:
      - ./db/data.${CORPUS_LANG}/:/var/lib/postgresql/data/
      - ./db/init.${CORPUS_LANG}/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bogoslov -U bogoslov"]
    restart: always

  populate:
    image: bogoslov
    environment:
      - LANGUAGE=${CORPUS_LANG}
      - HF_HOME=/models/
    volumes:
      - ./corpora.${CORPUS_LANG}/:/corpora/:ro
      - ./models/:/models/
    command: ./populate.py -v -n -e
    # command: ./populate.py -e
    # command: ./populate.py --embedding=sentence-transformers/LaBSE
    # command: tail -f /dev/null
    restart: no
    depends_on:
      - db
